### ISSUE TITLE
关于数据集的一些疑惑

### ISSUE THREAD

**Issue by Jarvis-K** [Autumn945/MOOD#1]
你好，我在看这个代码使用的数据集时看到其中的location是一个整数，不知是怎么转换的呢，感觉如果用onehot的话是应该一个list，想知道是做了怎样的预处理得到的

**Comment by Autumn945** [comment]
先编号为一个整数，之后再编码成one-hot是很方便的（索引单位矩阵中的那一行就可以得到了）。
如果直接用one-hot存取比较低效，而且keras(或者别的深度学习框架也一样)中用Embedding，输入就是一个编号，而不是one-hot，因为这样实现起来更有效率。
公式里面写的是先编码为one-hot，再与一个Embedding矩阵相乘，这是为了更公式化和便于理解。
实际Embedding的实现就是按编号去Embedding矩阵里面查找某一列了。

**Comment by Jarvis-K** [comment]
好的，十分感谢。
因为之前没用深度学习处理过相关问题，所以产生了这样的疑问，听作者说完清楚了很多，所以现在Close这个ISSUSE了
